// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnAfL7Q__4x6osgOSyZyu1qRVsQ1sYvGo',
    appId: '1:1044856833793:web:7bb5e1b6edbe954437bd00',
    messagingSenderId: '1044856833793',
    projectId: 'insta-1cc5a',
    authDomain: 'insta-1cc5a.firebaseapp.com',
    storageBucket: 'insta-1cc5a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3eMdI9jxj2tVKYSNurQMPYqZiLRBfUUQ',
    appId: '1:1044856833793:android:cf83e7a1568b86af37bd00',
    messagingSenderId: '1044856833793',
    projectId: 'insta-1cc5a',
    storageBucket: 'insta-1cc5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFFggHuluL6r18Yg3q_SXgCXaO1pwJ5qo',
    appId: '1:1044856833793:ios:d515066f646ca21737bd00',
    messagingSenderId: '1044856833793',
    projectId: 'insta-1cc5a',
    storageBucket: 'insta-1cc5a.firebasestorage.app',
    iosBundleId: 'com.example.insta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFFggHuluL6r18Yg3q_SXgCXaO1pwJ5qo',
    appId: '1:1044856833793:ios:d515066f646ca21737bd00',
    messagingSenderId: '1044856833793',
    projectId: 'insta-1cc5a',
    storageBucket: 'insta-1cc5a.firebasestorage.app',
    iosBundleId: 'com.example.insta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnAfL7Q__4x6osgOSyZyu1qRVsQ1sYvGo',
    appId: '1:1044856833793:web:3e361a6ae5fb995c37bd00',
    messagingSenderId: '1044856833793',
    projectId: 'insta-1cc5a',
    authDomain: 'insta-1cc5a.firebaseapp.com',
    storageBucket: 'insta-1cc5a.firebasestorage.app',
  );
}
